services:
  - type: web
    name: leakosint-webhook
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: LEAKOSINT_API_TOKEN
        sync: false
      - key: WEBHOOK_PATH
        value: /webhook
      - key: UPI_ID
        value: your-upi@bank
      - key: ADMIN_IDS
        value: ""   # comma separated admin telegram ids, e.g. "12345678,23456789"
