services:
  - type: web
    name: leakosint-webhook
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: LEAKOSINT_API_TOKEN
        sync: false
      - key: WEBHOOK_PATH
        value: /webhook
